### ISSUE TITLE
npm package missing

### ISSUE THREAD

**Issue by vu-dang** [ben-hynt/react-native-fyber#1]

**Comment by bsy** [comment]
Sorry for the delay, was on vacation, will add soon!

**Comment by SaidTayebi** [comment]
Hi, great work !
Are planning in developing The banner and interstitial Ad ?

**Comment by SaidTayebi** [comment]
I'm working on an App built on React-Native that needs to interact with many Ad providers (nativeX, AdMob, Fyber, AERSERV, ...).
Since you have exeprience with RN and Fyber, what's the best way to proceed without using the SDK ?
Implementing Bridges ? using API if available ?

**Comment by bsy** [comment]
@SaidTayebi I may add the banner ad and interstitial support soon, in the meantime more than welcome a PR if you are able to add it!  As for the other question, Fyber already meditates all the ad networks so you just need to install the adapters and then configure each network within Fyber's interface.  

Also @vu-dang I just published to NPM
